version: '3.8'

services:
  worker-1:
    image: rust:alpine
    container_name: worker-1
    command: sleep infinity  # Mantiene el contenedor vivo
    restart: always

  worker-2:
    image: rust:alpine
    container_name: worker-2
    command: sleep infinity
    restart: always

  worker-3:
    image: rust:alpine
    container_name: worker-3
    command: sleep infinity
    restart: always

  worker-4:
    image: rust:alpine
    container_name: worker-4
    command: sleep infinity
    restart: always
