[package]
name = "connection-tcp"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hub"
path = "src/bin/hub.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
socket2 = { version = "0.5", features = ["all"] }
dotenvy = "0.15"