services:
  hub:
    build: 
      context: .
      dockerfile: Dockerfile.hub
    network_mode: "host" 

  cliente_local:
    build:
      context: .
      dockerfile: Dockerfile.client
    network_mode: "host"
    environment:
      - SERVER_ADDR=10.10.10.1:7878 # Usa la IP de la VPN, no el nombre del servicio